# Generated by Django 5.2.12 on 2026-04-10 08:49

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_family_role_fields'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('directory', '0002_families_table_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^[0-9+()\\-\\s]{7,20}$')], verbose_name='Phone number'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['area_ward'], name='accounts_area_ward_idx'),
        ),
    ]
