# Generated by Django 5.2.12 on 2026-04-10 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_weekly_schedule_rule_service_slots'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_one', models.ImageField(upload_to='banners/')),
                ('banner_two', models.ImageField(upload_to='banners/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_banners_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dashboard_banners',
            },
        ),
    ]
