# Generated by Django 5.2.12 on 2026-04-10 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_legacy_banners(apps, schema_editor):
    DashboardBanner = apps.get_model('events', 'DashboardBanner')
    DashboardBannerImage = apps.get_model('events', 'DashboardBannerImage')

    if DashboardBannerImage.objects.exists():
        return

    legacy = DashboardBanner.objects.order_by('-updated_at', '-id').first()
    if not legacy:
        return

    created_by_id = getattr(legacy, 'updated_by_id', None)
    sort_order = 1

    banner_one = getattr(legacy, 'banner_one', None)
    if banner_one:
        DashboardBannerImage.objects.create(
            image=banner_one,
            sort_order=sort_order,
            is_active=True,
            created_by_id=created_by_id,
        )
        sort_order += 1

    banner_two = getattr(legacy, 'banner_two', None)
    if banner_two:
        DashboardBannerImage.objects.create(
            image=banner_two,
            sort_order=sort_order,
            is_active=True,
            created_by_id=created_by_id,
        )


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_dashboardbanner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardBannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_banner_images_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dashboard_banner_images',
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='banner_active_sort_idx')],
            },
        ),
        migrations.RunPython(copy_legacy_banners, noop_reverse),
    ]
